=== cornelius/kode/kxforms/tests/features.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified"
  xmlns:ugh="http://www.kde.org/standards/ugh/0.1" >
  
  <xs:annotation>
    <xs:documentation>
      This Schema describes the KDE Feature Plan document.
    </xs:documentation>
    <xs:appinfo>
      <ugh:hint>
        <ugh:label>KDE Feature Schema</ugh:label>
      </ugh:hint>
    </xs:appinfo>
  </xs:annotation>
  
  <xs:element name="features">
    <xs:annotation>
      <xs:documentation>
        Top-level element containing all the top-level categories.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="category"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="category">
    <xs:annotation>
      <xs:appinfo>
        <ugh:hint ref="feature">
          <ugh:label>Feature: <arg ref="summary" truncate="50"/></ugh:label>
        </ugh:hint>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="feature"/>
        <xs:element ref="category"/>
      </xs:choice>
      <xs:attributeGroup ref="attlist.category"/>
    </xs:complexType>
  </xs:element>
  
  <xs:attributeGroup name="attlist.category">
    <xs:attribute name="name" use="required"/>
  </xs:attributeGroup>
  
  <xs:element name="feature">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="summary"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="responsible"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.feature"/>
    </xs:complexType>
  </xs:element>
  
  <xs:attributeGroup name="attlist.feature">
    <xs:attribute name="status" default="todo">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="todo"/>
          <xs:enumeration value="inprogress"/>
          <xs:enumeration value="done"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="target" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="3.4"/>
          <xs:enumeration value="3.5"/>
          <xs:enumeration value="4.0"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  
  <xs:element name="responsible">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.responsible"/>
    </xs:complexType>
  </xs:element>
  
  <xs:attributeGroup name="attlist.responsible">
    <xs:attribute name="name"/>
    <xs:attribute name="email"/>
  </xs:attributeGroup>
  
  <xs:element name="summary">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="i"/>
        <xs:element ref="a"/>
        <xs:element ref="b"/>
        <xs:element ref="em"/>
        <xs:element ref="strong"/>
        <xs:element ref="br"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="i" type="xs:string"/>
  
  <xs:element name="b" type="xs:string"/>

  <xs:element name="em" type="xs:string"/>

  <xs:element name="strong" type="xs:string"/>

  <xs:element name="br">
    <xs:complexType/>
  </xs:element>

  <xs:element name="a">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.a"/>
    </xs:complexType>
  </xs:element>

  <xs:attributeGroup name="attlist.a">
    <xs:attribute name="href"/>
    <xs:attribute name="title"/>
  </xs:attributeGroup>

</xs:schema>

=== cornelius/kode/docs/example.xml
<?xml version='1.0' encoding='UTF-8'?>
<features xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://www.kde.org/standards/features/1.0"
  xsi:schemaLocation="http://www.kde.org/standards/features/1.0
                      http://www.kde.org/standards/features/1.0/features.xsd" >
  <category name="KDE PIM (Personal Information Management)" >
    <category name="Kontact" >
      <feature status="done">
        <summary>Merged configuration view.</summary>
      </feature>
      <feature status="todo">
        <summary>Add alternative tab-based viewmode.</summary>
      </feature>
    </category>
    <category name="KOrganizer" >
      <category name="Merge of KO/Pi code" >
        <feature status="inprogress">
          <summary>DateNavigator</summary>
        </feature>
        <feature status="todo">
          <summary>Printing: layout bug-fixing and more.</summary>
        </feature>
        <feature status="todo">
          <summary>Printing of what's next view.</summary>
        </feature>
      </category>
      <feature status="done">
        <summary>Moving / detaching recurring events in the agenda
        view</summary>
      </feature>
      <feature status="todo">
        <summary>tighter integration with KNotes - ability to pin a note to a
        contact</summary>
      </feature>
    </category>
  </category>
</features>
